### ISSUE TITLE
Application doesn't start

### ISSUE THREAD

**Issue by pvdochtend** [riverar/draconyx#1]
Hi there,

I tried to start the application (downloaded here) but an empty window is showing very shortly and then it disappears.

Then I tried to use the source code to check / debug why this goes wrong.
I am not very experienced with Visual Studio but even with google I can't get the references correct to get it to build :(

**Comment by wesley974** [comment]
Get same issue

**Comment by Erwan-LB** [comment]
Error in Draconyx.csproj: hint path are relatives.
<HintPath>..\..\Program Files (x86) [....]
should be
<HintPath>C:\Program Files (x86)\ [...]

Or you must use your solution from a folder nested in a subfolder (ie: c:\test\Draconyx-master for example).
