### ISSUE TITLE
Hi, thank you for the code.

### ISSUE THREAD

**Issue by antoniohlopes** [riverar/draconyx#3]
I cannot found the "Windows.Devices.Bluetooth", the dll is missing.
But, I can run the executable draconyx.exe. This means that the dlls are in my system.
How I can add the WIndows.Foundation to the my project (draconyx)
Thank you
Antonio
![Screenshot 2021-02-22 133208](https://user-images.githubusercontent.com/12420488/108662873-a0a59780-7512-11eb-886f-dad52bba4be3.jpg)
![Screenshot 2021-02-22 140124](https://user-images.githubusercontent.com/12420488/108664630-7bb32380-7516-11eb-9be4-b88328db765e.jpg)

**Comment by Erwan-LB** [comment]
Error in Draconyx.csproj: hint path are relatives.
`<HintPath>..\..\Program Files (x86) [....]`
 should be 
`<HintPath>C:\Program Files (x86)\ [...]`

Or you must use your solution from a folder nested in a subfolder (ie: c:\test\Draconyx-master for example).

**Comment by antoniohlopes** [comment]
Hi Erwan-LB,
Thank you. I get it.
In my system, there are sub-folder with OS build version, like '10.0.18362.0'; and is my first time that do a reference to '**winmd**'.
![Screenshot 2021-03-01 185307](https://user-images.githubusercontent.com/12420488/109481088-b04b5000-7abf-11eb-9901-185612d10de1.jpg)

but, yet and can't fix problems with Windows 10 'dynamic look'.
